# Python Basics

Python is an open-source programming language known for its simplicity and readability. It is quite versatile, and can be used for both scripting applications and standalone programs. It is a popular choice for almost all data analysis and machine learning projects.

In this section, we will give a very brief overview of some fundamental Python concepts.

## The Very Basics: Variables, Syntax, and Data Types

Like any other programming language, Python can be used as a calculator.

To test this, just position your cursor in the below cell and hit Ctrl+Enter (Command+Enter on Mac). Alternatively, you can click the play button on the left gutter of the cell.

In [1]:
2 + 3

5

A standard programming practice is to store our values in variables.

In [ ]:
x = 12
y = 3
x + y

15

In the above cell, numbers `12` and `3` are stored in variables `x` and `y` respectively. Each variable is automatically assigned a type. In this case, both `x` and `y` are integers (`int`).

Below is a list of some of the basic data types in Python:

* `int`: an integer, like `123`.
* `float`: a floating-point number, like `1.23`.
* `str`: a string, like `"Hello, world!"`.
* `bool`: a boolean value, like `True` or `False`.




You can use the `type()` function to get the data type of a variable.

In [ ]:
name = "Alice"
type(name)

str

Python also allows you to convert from one data type to another. This can sometimes help resolve value errors when working with real datasets.

In [ ]:
z = 10
float(10)

10.0

Finally, you can use the `print` function to write the value of a variable to the screen.

In [ ]:
print(x)
print(y)
print(x+y, x-y, x*y, x/y, y**2)
print(f"My name is {name}")

12
3
15 9 36 4.0 9
My name is Alice


## Conditionals and Loops

Conditionals and loops are essential tools for any programmer. They allow us to automate tasks and build complex logic into our programs.

In Python, we use the `if`, `elif`, and `else` keywords to define conditional statements. The `elif` and `else` blocks are optional, and you can include as many `elif` blocks as you want.

As for loops, we use the `for` keyword to define a loop. The `range()` function is a convenient way to generate a sequence of numbers that can be used to iterate over a `for` loop.

In [66]:
x = 15
if x > 10:
    print("x is greater than 10")

x is greater than 10


In [84]:
for i in range(10):
    print(i, end = ' ')

0 1 2 3 4 5 6 7 8 9 

In [83]:
# Exercise 1. Extend the first example to print only if between 10 and 13: $ x \in (10, 13)$
x = 13
if 10 < x < 13: 
    print("x is between 10 and 13")

In [72]:
# Exercise 2. Implement the factorial function using a for loop. Remember the factorial of a number n is the product of all the numbers from 1 to n. For example, the factorial of 5 is 5*4*3*2*1 = 120.
def factorial(n):
    prod = 1
    for i in range(1, n+1):
        prod *= i
    return prod

factorial(5)

120

## Lists and Dictionaries

Apart from the basic built-in data types introduced in the previous sub-section, there are a few more interesting data types in Python.

Let us look at lists and dictionaries, the two data types that you will almost always encounter while working on any machine learning project. Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.

**Lists**

A list is an ordered collection of elements. Here is how you can create a list in python


In [2]:
# Creating a list
my_list = [1,2,3,4,5]
type(my_list)

list

Every item in a list is assigned an index. Keep in mind that indices in Python always start with 0. In other words, the first item in a list has index 0, the second item has index 1, and so on.

You can access any item in a list by its index using square brackets `[]`. For instance:



In [4]:
# Accessing list items
first_element = my_list[0]
last_element = my_list[-1]

print("Original List:", my_list)
print("First Element:", first_element)
print("Last Element:", last_element)


Original List: [1, 2, 3, 4, 5]
First Element: 1
Last Element: 5


Apart from accessing single elements in a list, it is also possible to access any sub-part of a list. You can achieve this using a techinque called *list slicing*.

In [5]:
# Slicing
subset = my_list[1:4]
subset

[2, 3, 4]

Lists are changable. This means that you can change, add or remove items from a list after it has been created.



In [9]:
my_list[0] = 6
my_list

[6, 2, 3, 4, 5]

List items allow duplicate values.


In [13]:
# Appending elements
my_list.append(6)
print("List After Appending:", my_list)

# Extending with another list
another_list = [7, 8, 9]
my_list.extend(another_list)
print("Extended List:", my_list)

# Removing elements
my_list.remove(4)
print("List After Removing:", my_list)

# Popping an element
popped_element = my_list.pop(3)
print("Popped Element:", popped_element)
print("List After Popping:", my_list)

# Finding the index of an element
index_of_8 = my_list.index(8)
print("Index of 8:", index_of_8)

# Checking if an element is in the list
is_present = 6 in my_list
print("Is 6 present in the list?", is_present)

# Reversing the list
my_list.reverse()
print("Reversed List:", my_list)

# Sorting the list
my_list.sort()
print("Sorted List:", my_list)


List After Appending: [6, 2, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6]
Extended List: [6, 2, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9]
List After Removing: [6, 2, 3, 5, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9]
Popped Element: 5
List After Popping: [6, 2, 3, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9]
Index of 8: 5
Is 6 present in the list? True
Reversed List: [9, 8, 7, 6, 9, 8, 7, 6, 9, 8, 7, 6, 9, 8, 7, 6, 3, 2, 6]
Sorted List: [2, 3, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]


__Dictionaries__ Another key data-structure is the dictionary. It is similar to a list, but each element is a key-value pair. The key can be used to retrieve the corresponding value from the dictionary. Here is how you can create and manipulate a dictionary in Python.

In [15]:
# Dictionary 'dict': key-value pairs

# Creating a dictionary
my_dict = {
    'name': 'John',
    'age': 25,
    'city': 'New York',
    'is_student': False
}

# Accessing values
name_value = my_dict['name']
age_value = my_dict.get('age', 'N/A')  # Using get() to handle missing keys

print("Original Dictionary:", my_dict)
print("Name:", name_value)
print("Age:", age_value)

# Modifying values
my_dict['age'] = 26
my_dict['is_student'] = True
my_dict['occupation'] = 'Engineer'  # Adding a new key-value pair

print("Modified Dictionary:", my_dict)

# Removing key-value pairs
removed_value = my_dict.pop('city', 'N/A')  # Using pop() to remove and retrieve
del my_dict['is_student']  # Using del to remove a key-value pair

print("Dictionary After Removals:", my_dict)
print("Removed City Value:", removed_value)

# Checking if a key is present
is_present = 'occupation' in my_dict
print("Is 'occupation' present?", is_present)

# Getting keys, values, and items
keys = my_dict.keys()
values = my_dict.values()
items = my_dict.items()

print("Keys:", keys)
print("Values:", values)
print("Items:", items)

# Copying a dictionary
copied_dict = my_dict.copy()
print("Copied Dictionary:", copied_dict)

# Clearing a dictionary
my_dict.clear()
print("Cleared Dictionary:", my_dict)


Original Dictionary: {'name': 'John', 'age': 25, 'city': 'New York', 'is_student': False}
Name: John
Age: 25
Modified Dictionary: {'name': 'John', 'age': 26, 'city': 'New York', 'is_student': True, 'occupation': 'Engineer'}
Dictionary After Removals: {'name': 'John', 'age': 26, 'occupation': 'Engineer'}
Removed City Value: New York
Is 'occupation' present? True
Keys: dict_keys(['name', 'age', 'occupation'])
Values: dict_values(['John', 26, 'Engineer'])
Items: dict_items([('name', 'John'), ('age', 26), ('occupation', 'Engineer')])
Copied Dictionary: {'name': 'John', 'age': 26, 'occupation': 'Engineer'}
Cleared Dictionary: {}


## Hands-On Exercise: Python Basics


Use list comprehension to create two lists
1. First 10 multiples of 2
2. First 10 multiple of 3

3. Now count the number of common multiples of 2 and 3 in the above lists

Did you solve 3. using for loops? Can you also solve it using list comprehensions?

In [48]:
# TODO Solution remove
lst_1 = [2*(i+1) for i in range(10)]
lst_2 = [3*(i+1) for i in range(10)]
[each for each in lst_1 if each in lst_2]

[6, 12, 18]

## Python Functions and Classes

We can create reusable code in Python using functions and classes. Let's start with functions.

We can define a function using the `def` keyword. Here is an example of a function that takes two numbers as input and returns their sum.

In [49]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [52]:
# Exercise: create a function to subtract two numbers
# TODO Solution remove
def subtract_numbers(x, y):
    return x - y

subtract_numbers(1, 2)

-1

We can also create classes in Python. Here is an example of a class that represents a Person. A class can contain data in the form of attributes as well as functions in the form of methods.

In [61]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def greet(self):
        print(f"Hello, my name is {self.name} and I'm {self.age} years old.", end = " ")

person = Person("John", 25)
person.greet()

Hello, my name is John and I'm 25 years old. 

Classes can also inherit from other classes. Here is an example of a class that inherits from the Person class and adds a new attribute.

In [64]:
# Exercise: add a new attribute major to the Student class and print it in the greet() method.

# TODO Solution remove
class Student(Person):
    def __init__(self, name, age, major):
        super().__init__(name, age)
        #self.major = major
            
    def greet(self):
        super().greet()
        #print(f"I'm a student majoring in {self.major}.")

student = Student("Alice", 20, "Computer Science")
student.greet()

Hello, my name is Alice and I'm 20 years old. 

## Hands-On Exercise: Python Functions and Classes

# Introduction to NumPy



## NumPy Overview
- Fundamental library for numerical operations.
- Creating arrays, basic operations, and indexing.
- Advantages of NumPy arrays over traditional lists.
- Illustrate vectorized operations for efficiency.



Importing NumPy

In [27]:
import numpy as np

In [28]:
# Creating NumPy arrays
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[7, 8, 9], [10, 11, 12]])
print("Array A:\n", array_a)
print("Array B:\n", array_b)

Array A:
 [[1 2 3]
 [4 5 6]]
Array B:
 [[ 7  8  9]
 [10 11 12]]


In [29]:
# Element-wise operations
elementwise_sum = array_a + array_b
elementwise_difference = array_a - array_b
elementwise_product = array_a * array_b
elementwise_division = array_a / array_b
print("\nElement-wise Sum:\n", elementwise_sum)


Element-wise Sum:
 [[ 8 10 12]
 [14 16 18]]


In [30]:
# Dot product
dot_product = np.dot(array_a, array_b.T)
print("Dot Product:\n", dot_product)

# Transposing an array
transposed_array_a = array_a.T

# Broadcasting
broadcasted_array = array_a + 10

print("\nTransposed Array A:\n", transposed_array_a)
print("\nBroadcasted Array A:\n", broadcasted_array)

Dot Product:
 [[ 50  68]
 [122 167]]

Transposed Array A:
 [[1 4]
 [2 5]
 [3 6]]

Broadcasted Array A:
 [[11 12 13]
 [14 15 16]]


In [31]:
# Universal functions (ufunc)
logarithm_values = np.log(array_a)
square_root_values = np.sqrt(array_a)
print("\nLogarithm Values:\n", logarithm_values)
print("Square Root Values:\n", square_root_values)

# Aggregation functions
mean_value = np.mean(array_a)
sum_value = np.sum(array_a)
max_value = np.max(array_a)
print("\nMean Value:", mean_value)
print("Sum Value:", sum_value)
print("Max Value:", max_value)

# Indexing and slicing
first_row = array_a[0, :]
second_column = array_a[:, 1]
print("\nFirst Row:\n", first_row)
print("Second Column:\n", second_column)

# Reshaping arrays
reshaped_array = array_a.reshape((3, 2))
print("\nReshaped Array:\n", reshaped_array)

# Stacking arrays
stacked_horizontally = np.hstack((array_a, array_b))
stacked_vertically = np.vstack((array_a, array_b))
print("\nHorizontally Stacked:\n", stacked_horizontally)
print("Vertically Stacked:\n", stacked_vertically)

# Random number generation
random_array = np.random.rand(2, 3)
print("\nRandom Array:\n", random_array)


Logarithm Values:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
Square Root Values:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

Mean Value: 3.5
Sum Value: 21
Max Value: 6

First Row:
 [1 2 3]
Second Column:
 [2 5]

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]

Horizontally Stacked:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertically Stacked:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Random Array:
 [[0.53739752 0.61644625 0.66236946]
 [0.45795849 0.37323453 0.8730773 ]]


## 2.2 Hands-On Exercise: NumPy Basics

Now we understand the basics of NumPy. Let us try to solve a few problems using NumPy.

1. Convert the temperature values from Fahrenheit to Celsius. The formula for conversion is: `C = (F - 32) * 5/9`. You can use the `numpy.array()` function to create a NumPy array from a Python list.

In [87]:
# Let's create an array of typical winter farenheit values
farenheit = np.array([0,-10,-5,-15,0])

# TODO: Convert farenheit to celcius
raise NotImplementedError("TODO: Implement the conversion from farenheit to celcius")
#celcius = (farenheit - 31) * (5/9)
#celcius

NotImplementedError: TODO: Implement the conversion from farenheit to celcius

In [88]:
# 2. Given a NumPy array, find out the mean, median, standard deviation, and variance of its values. You can use the `numpy.mean()`, `numpy.median()`, `numpy.std()`, and `numpy.var()` functions respectively.
a = np.array([1,2,3,4,5,6,7,8,9,10])
#raise NotImplementedError("TODO: Implement this!")
#print(a.mean())
#print(a.median())
#print(a.std())

In [90]:
# 3. Given a NumPy array, normalize it so that all values are between 0 and 1. Implement min-max normalization using the equation below:
# x = (x - min(x)) / (max(x) - min(x))

a = np.array([1,2,3,4,5,6,7,8,9,10])
#raise NotImplementedError("TODO: Implement min-max normalization")
#a = (a - a.min()) / (a.max() - a.min())
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Introduction to Matplotlib

# BONUS: Linear Regression with NumPy


Remember that the key goal of machine learning is to, given some training data, develop an accurate model of the data that can be used to make predictions about new data. Linear regression is an example of such a method. This notebook explores the basics of linear regression using NumPy and Matplotlib. You will learn how to implement the method from scratch and use it to fit a line to a set of data points.

We now invite you to review the material in https://compneuro.neuromatch.io/tutorials/W1D2_ModelFitting/student/W1D2_Tutorial1.html#. Proceed by opening the notebook in Colab and running the code cells.




# Resources

- python basics: https://developers.google.com/edu/python AND https://mbakker7.github.io/exploratory_computing_with_python/
- Official python documentation: https://docs.python.org/3/
- For linear regression: https://compneuro.neuromatch.io/tutorials/W1D2_ModelFitting/student/W1D2_Tutorial1.html#